learning_users/basic_app/urls.py
from django.urls import path, re_path, include
from basic_app import views

app_name = 'basic_app'

urlpatterns=[
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^user_login/$', views.user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^basic_app/', include('basic_app.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout')
    
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    """docstring for UserProfileInfo."""
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING,)

    # Additional

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    """docstring for UserForm."""
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        """docstring for ."""
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save();
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):
    if request.method == "POST":
        username = request.POST.get('uname')
        password = request.POST.get('pswd')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active.")
        else:
            print("Someone tried to login and failed.")
            print("Username: {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="navbar-brand" href="{%url 'index'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'admin:index'%}">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{%url 'basic_app:register'%}">Register</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'logout'%}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'basic_app:user_login'%}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>


    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

learning_users/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Django level five</h1>

  </div>

{% endblock %}

learning_users/templates/basic_app/login.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Please login</h1>
    <form action="{% url 'basic_app:user_login' %}" class="was-validated" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="uname">Username:</label>
        <input type="text" class="form-control" id="uname" placeholder="Enter username" name="uname" required>
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Please fill out this field.</div>
      </div>
      <div class="form-group">
        <label for="pwd">Password:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd" required>
        <div class="valid-feedback">Valid.</div>
        <div class="invalid-feedback">Please fill out this field.</div>
      </div>
      <div class="form-group form-check">
        <label class="form-check-label">
          <input class="form-check-input" type="checkbox" name="remember" required> I agree on blabla.
          <div class="valid-feedback">Valid.</div>
          <div class="invalid-feedback">Check this checkbox to continue.</div>
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>

{% endblock %}

learning_users/templates/basic_app/registration.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thanks you for regestring!</h1>
    {% else %}
      <h1>Register here!</h1>
      <h3>Fillout the form:</h3>

      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>

{% endblock %}